# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16a09476ae47989970c2937f1bcac2533f3db55a55224a9192efb497918e216c9de9073d579e6eb85823572665840fca342b2b7263c55c1a60e9db3c1325d18e

test:
  secret_key_base: 0033230ff472b7331b110ac6289880a8526a3358d235eff773c399e6ae89a5c6a224a9ecd03119b30395eda2d76b369fd41c0df6bd45b9d761242b51cf4026bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
